### ISSUE TITLE
Compatibility with gulp-protractor

### ISSUE THREAD

**Issue by nitsanfri** [NickTomlin/protractor-flake#43]
Hey,

I was wondering if someone managed to integrate protractor-flake with the gulp-protractor project (https://github.com/mllrsohn/gulp-protractor).

I was trying to create the following gulp task:

gulp.task("test-e2e-new", function(){
  gulp.src(path.join(consts.appRoot, 'test/**/*.js'))
    .pipe(protractorFlake({
      maxAttempts: 3,
      protractorPath: './gulp/protractor.conf.js'
    }, function (status, output) {
      process.exit(status);
    }))
    .on('error', function(e) {console.log(e); });
});

However, when i'm trying to run it I get:

[09:20:28] Using gulpfile /Volumes/case_sensitive/dev/myCompany/trunk/myService/build/gulpfile.js
[09:20:28] Starting 'test-e2e-new'...
[09:20:28] 'test-e2e-new' errored after 11 ms
[09:20:28] TypeError: Cannot read property 'on' of undefined
    at DestroyableTransform.Readable.pipe (/Volumes/case_sensitive/dev/myCompany/trunk/myService/build/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:516:7)
    at Gulp.<anonymous> (/Volumes/case_sensitive/dev/myCompany/trunk/myService/build/gulp/test.gulp.js:34:6)
    at module.exports (/Volumes/case_sensitive/dev/myCompany/trunk/myService/build/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Volumes/case_sensitive/dev/myCompany/trunk/myService/build/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Volumes/case_sensitive/dev/myCompany/trunk/myService/build/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Volumes/case_sensitive/dev/myCompany/trunk/myService/build/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)

Any suggestions?

Thanks a lot!

**Comment by NickTomlin** [comment]
Unfortunately the gulp paradigm is a little forced with protractor and protractor flake (since at the end of the day, neither supports "streaming" of files). If you want to use gulp to kick off a protractor flake task, the following should suffice:

```
gulp.task("test-e2e-new", function(callback){
  protractorFlake({
    protractorArgs: ['./gulp/protractor.conf.js', '--specs', path.join(consts.appRoot, 'test/**/*.js')]
  }, function (status) {
    if (status === 0) {
      callback();
    } else {
      callback('Test Failiure: ' + status);
    }
  });
});
```

**Comment by nitsanfri** [comment]
Thanks so much! It looks much better. It actually runs 3 times (3 retires), however all tests fails due to
(I don't know if this is your scope though...).
This is the error I get from all the test:

Project Name - Test Name
    ✗ should not display the table when the page is loaded without params
      - Failed: JavascriptError
          at /Volumes/case_sensitive/dev/myCompany/trunk/MyProject/build/node_modules/protractor/node_modules/jasminewd2/index.js:101:16
          at Promise.invokeCallback_ (/Volumes/case_sensitive/dev/myCompany/trunk/MyProject/build/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
          at TaskQueue.execute_ (/Volumes/case_sensitive/dev/myCompany/trunk/MyProject/build/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
          at TaskQueue.executeNext_ (/Volumes/case_sensitive/dev/myCompany/trunk/MyProject/build/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)

Thanks again for the help!

**Comment by nitsanfri** [comment]
It's a bug on my end.
All looks great now! :)

Thanks again for the help - super happy to use your lib

**Comment by NickTomlin** [comment]
glad it worked, thanks 😄 !
