### ISSUE TITLE
ERROR: 'missing ) after argument list

### ISSUE THREAD

**Issue by Tom-Hudson** [NickTomlin/protractor-flake#66]
I am getting an error when running protractor-flake. I am trying to use a npm script but it gives me the following error:

**Error**
```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3
```

**npm logs**
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\073349\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'flake' ]
2 info using npm@5.3.0
3 info using node@v7.6.0
4 verbose run-script [ 'preflake', 'flake', 'postflake' ]
5 info lifecycle protractor-tests@1.0.0~preflake: protractor-tests@1.0.0
6 info lifecycle protractor-tests@1.0.0~flake: protractor-tests@1.0.0
7 verbose lifecycle protractor-tests@1.0.0~flake: unsafe-perm in lifecycle true
8 verbose lifecycle protractor-tests@1.0.0~flake: PATH: C:\Users\073349\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Projects\Unity\Dev\ProtractorTests\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Java\jre6\bin\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)\Common Files\Siemens\System;C:\Users\073349\.cargo\bin;C:\texlive\2016\bin\win32;C:\Program Files\Common Files\Intel\WirelessCommon\C:\Users\073349\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\073349\AppData\Roaming\npm
9 verbose lifecycle protractor-tests@1.0.0~flake: CWD: C:\Projects\Unity\Dev\ProtractorTests
10 silly lifecycle protractor-tests@1.0.0~flake: Args: [ '/d /s /c',
10 silly lifecycle   'protractor-flake --protractor-path=node_modules/.bin/protractor --parser=standard --max-attempts=2 --local.conf.js' ]
11 silly lifecycle protractor-tests@1.0.0~flake: Returned: code: 1  signal: null
12 info lifecycle protractor-tests@1.0.0~flake: Failed to exec flake script
13 verbose stack Error: protractor-tests@1.0.0 flake: `protractor-flake --protractor-path=node_modules/.bin/protractor --parser=standard --max-attempts=2 --local.conf.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\073349\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:192:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\073349\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:192:7)
13 verbose stack     at maybeClose (internal/child_process.js:890:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid protractor-tests@1.0.0
15 verbose cwd C:\Projects\Unity\Dev\ProtractorTests
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\073349\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "flake"
18 verbose node v7.6.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error protractor-tests@1.0.0 flake: `protractor-flake --protractor-path=node_modules/.bin/protractor --parser=standard --max-attempts=2 --local.conf.js`
22 error Exit status 1
23 error Failed at the protractor-tests@1.0.0 flake script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**package.json - script**
```
 "flake": "node_modules/.bin/protractor-flake --protractor-path=node_modules/.bin/protractor --parser=standard --max-attempts=2 --local.conf.js"
```

All the node_modules directory references etc. seem right and the files all appear to be there. I don't think I am doing anything wrong - but suspect I might be as nobody else is having this issue?

- Windows 7 (64 bit)
- Node.js v7.6.0
- Protractor v5.1.2
- Protractor flake v2.5.1

**Comment by NickTomlin** [comment]
This looks similar to https://github.com/NickTomlin/protractor-flake/issues/64 which was an issue with windows and node `.bin`s. I'm unfamiliar with how node on windows functions here but you should be able to resolve this by altering your command to ommit the paths. NPM should resolve to the correct executable without needing to specify it and protractor-flake will look up protractor for you.

```
 "flake": "protractor-flake  --parser=standard --max-attempts=2 --protractor-path=node_modules/.bin/protractor -- local.conf.js"
```

Let me know if that helps.

**Comment by Tom-Hudson** [comment]
@NickTomlin - this sadly didn't help me. I changed the script to be exactly the same as you provided and it gave the same error.

Any other ideas?

**Comment by Tom-Hudson** [comment]
@NickTomlin - I re-read your comment and didn't blindly copy and paste this time :)

Omitting `--protractor-path=node_modules/.bin/protractor` fixed this issue !

here is what i ended up with:
```
 "flake": "protractor-flake  --parser=standard --max-attempts=2 -- local.conf.js"
```

**Comment by NickTomlin** [comment]
@hudson-t great, glad to hear that it worked! 

If you have some spare time i'd appreciate a pull request that fixes or clarifies this for other windows users.

**Comment by Tom-Hudson** [comment]
@NickTomlin - thanks for your help! I will update the the documentation later this week.

**Comment by vishal-chandale** [comment]
@NickTomlin  Thanks for this , it helped me as well.
