### ISSUE TITLE
protractor flake re running only last failure spec 

### ISSUE THREAD

**Issue by surendraJ** [NickTomlin/protractor-flake#77]
I am experiencing protractor flake re running only last failure spec file. Also interesting thing if there is only one failure spec then it re run all specs... 

OS- Window 7, Node.js - 6.9.5 , Protractor- 5.1.2, Protractor-flake - 3.0.0
---protractor configuration file------ 
```js
var HtmlScreenshotReporter = require('protractor-jasmine2-screenshot-reporter');
var htmlReporter = new HtmlScreenshotReporter({
	 	dest: 'e2e/testreports', 
	    filename: 'e2eReport.html', 
	    reportOnlyFailedSpecs: false,
		captureOnlyFailedSpecs: true, 
		showSummary: true,
		showQuickLinks: true
});

exports.config = {
    seleniumServerJar: '../../node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.4.0.jar',
    specs: [some specs],
    framework:'jasmine2',
    baseUrl: some_url,
    multiCapabilities: [
        {browserName: 'chrome'}
    ],
    directConnect: true,

    onPrepare: function() {
        browser.driver.manage().window().maximize();
        browser.driver.manage().timeouts().setScriptTimeout(60000);
        jasmine.getEnv().addReporter(htmlReporter);
        var jasmineReporters = require('jasmine-reporters');
        jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter({
            consolidateAll: true,
            savePath: 'e2e/testreports',
            filePrefix: 'e2eReport'
        }));
    },
    
    jasmineNodeOpts:{
        onComplete: null,
        isVerbose: false,
        showColors:true,
        includeStackTrace:true,
        defaultTimeoutInterval: 120000,
        restartBrowserBetweenTests:true
    },

    // Setup the report before any tests start
    beforeLaunch: function() {
        return new Promise(function(resolve){
        	htmlReporter.beforeLaunch(resolve);
        });
    },

    // Close the report after all tests finish
    afterLaunch: function(exitCode) {
        return new Promise(function(resolve){
        	htmlReporter.afterLaunch(resolve.bind(this, exitCode));
        });
    } 
};
```
[protractor.conf.txt](https://github.com/NickTomlin/protractor-flake/files/1316028/protractor.conf.txt)

----- log file ------  

```shell
[16:30:47] Using gulpfile C:\mypro\gulpfile.js
[16:30:47] Starting 'RUN:E2E'...
[16:30:47] Starting 'webdriver_update'...
[16:30:49] I/http_utils - ignoring SSL certificate
[16:30:49] I/http_utils - ignoring SSL certificate
[16:30:49] I/http_utils - ignoring SSL certificate
[16:30:49] I/http_utils - ignoring SSL certificate
[16:30:49] I/http_utils - ignoring SSL certificate
[16:30:49] I/http_utils - ignoring SSL certificate
[16:30:49] I/update - chromedriver: file exists C:\mypro\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedri
ver_2.32.zip
[16:30:49] I/update - chromedriver: unzipping chromedriver_2.32.zip
[16:30:50] I/update - chromedriver: chromedriver_2.32.exe up to date
[16:30:50] I/update - selenium standalone: file exists C:\mypro\node_modules\protractor\node_modules\webdriver-manager\selenium\se
lenium-server-standalone-3.4.0.jar
[16:30:50] I/update - selenium standalone: selenium-server-standalone-3.4.0.jar
up to date
[16:30:51] I/update - geckodriver: file exists C:\mypro\node_modules\protractor\node_modules\webdriver-manager\selenium\geckodrive
r-v0.19.0.zip
[16:30:51] I/update - geckodriver: unzipping geckodriver-v0.19.0.zip
[16:30:51] I/update - geckodriver: geckodriver-v0.19.0.exe up to date
[16:30:51] Finished 'webdriver_update' after 3.96 s
[16:30:51] Starting 'e2e'...
[16:30:51] Finished 'e2e' after 17 ms
[16:30:51] Finished 'RUN:E2E' after 3.99 s
Report destination:   e2e\testreports\e2eReport.html
[16:30:53] W/driverProviders - Using driver provider directConnect, but also fou
nd extra driver provider parameter(s): seleniumServerJar
[16:30:53] I/launcher - Running 1 instances of WebDriver
[16:30:53] I/direct - Using ChromeDriver directly...

Failures:
1) #National Data Filter Category  - [national-data-filter.spec.js]  should have
  zeros da
ta
  Message:
    Expected 'actual (52,243)' to contain '(0)', 'expecting total has 0 data'.
  Stack:
    Error: Failed expectation
        at C:\mypro\e2e\spec\national-data-filter.
spec.js:44:17
        at elementArrayFinder_.then (C:\mypro\node
_modules\protractor\lib\element.ts:840:22)
        at ManagedPromise.invokeCallback_ (C:\mypr
o\node_modules\selenium-webdriver\lib\promise.js:1366:14)
        at TaskQueue.execute_ (C:\mypro\node_modul
es\selenium-webdriver\lib\promise.js:2970:14)
        at TaskQueue.executeNext_ (C:\mypro\node_m
odules\selenium-webdriver\lib\promise.js:2953:27)
        at asyncRun (C:\mypro\node_modules\seleniu
m-webdriver\lib\promise.js:2813:27)
        at C:\mypro\node_modules\selenium-webdrive
r\lib\promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:103:7)
  Message:
    Expected 'actual (52,243)' to contain '(0)', 'expecting
total has 0 data'.
  Stack:
    Error: Failed expectation
        at C:\mypro\e2e\spec\national-data-filter.
spec.js:48:17
        at elementArrayFinder_.then (C:\mypro\node
_modules\protractor\lib\element.ts:840:22)
        at ManagedPromise.invokeCallback_ (C:\mypro\node_modules\selenium-webdriver\lib\promise.js:1366:14)
        at TaskQueue.execute_ (C:\mypro\node_modul
es\selenium-webdriver\lib\promise.js:2970:14)
        at TaskQueue.executeNext_ (C:\mypro\node_m
odules\selenium-webdriver\lib\promise.js:2953:27)
        at asyncRun (C:\mypro\node_modules\seleniu
m-webdriver\lib\promise.js:2813:27)
        at C:\mypro\node_modules\selenium-webdrive
r\lib\promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:103:7)

2) #Deep Link Test - [pf-deeplink.spec.js]  should display the search result whe
n clicking on different deeplink 
  Message:
    Failed: No element found using locator: By(css selector, *[id="contentSearch
BodyPopularSearch"])
  Stack:
    NoSuchElementError: No element found using locator: By(css selector, *[id="c
ontentSearchBodyPopularSearch"])
        at WebDriverError (C:\mypro\node_modules\s
elenium-webdriver\lib\error.js:27:5)
        at NoSuchElementError (C:\mypro\node_modul
es\selenium-webdriver\lib\error.js:168:5)
        at elementArrayFinder.getWebElements.then (C:\mypro\node_modules\protractor\lib\element.ts:851:17)
        at ManagedPromise.invokeCallback_ (C:\mypro\node_modules\selenium-webdriver\lib\promise.js:1366:14)
        at TaskQueue.execute_ (C:\mypro\node_modul
es\selenium-webdriver\lib\promise.js:2970:14)
        at TaskQueue.executeNext_ (C:\mypro\node_m
odules\selenium-webdriver\lib\promise.js:2953:27)
        at asyncRun (C:\mypro\node_modules\seleniu
m-webdriver\lib\promise.js:2813:27)
        at C:\mypro\node_modules\selenium-webdrive
r\lib\promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:103:7)
    From: Task: Run it("should display the search result when clicking on differ
ent deeplink for local data") in control flow
        at Object.<anonymous> (C:\mypro\node_modul
es\jasminewd2\index.js:94:19)
        at C:\mypro\node_modules\jasminewd2\index.
js:64:48
        at ControlFlow.emit (C:\mypro\node_modules
\selenium-webdriver\lib\events.js:62:21)
        at ControlFlow.shutdown_ (C:\mypro\node_mo
dules\selenium-webdriver\lib\promise.js:2565:10)
        at shutdownTask_.MicroTask (C:\mypro\node_
modules\selenium-webdriver\lib\promise.js:2490:53)
        at MicroTask.asyncRun (C:\mypro\node_modul
es\selenium-webdriver\lib\promise.js:2619:9)
    From asynchronous test:
    Error
        at Suite.<anonymous> (C:\mypro\e2e\spec\pf
-deeplink.spec.js:15:6)
        at Object.<anonymous> (C:\mypro\e2e\spec\p
f-deeplink.spec.js:7:1)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)

3) #Deep Link Test - [pf-deeplink.spec.js]  should display the search result whe
n clicking on different deeplink for other 
  Message:
    Failed: No element found using locator: By(css selector, *[id="contentSearch
BodyPopularSearch"])
  Stack:
    NoSuchElementError: No element found using locator: By(css selector, *[id="c
ontentSearchBodyPopularSearch"])
        at WebDriverError (C:\mypro\node_modules\s
elenium-webdriver\lib\error.js:27:5)
        at NoSuchElementError (C:\mypro\node_modul
es\selenium-webdriver\lib\error.js:168:5)
        at elementArrayFinder.getWebElements.then (C:\mypro\node_modules\protractor\lib\element.ts:851:17)
        at ManagedPromise.invokeCallback_ (C:\mypro\node_modules\selenium-webdriver\lib\promise.js:1366:14)
        at TaskQueue.execute_ (C:\mypro\node_modul
es\selenium-webdriver\lib\promise.js:2970:14)
        at TaskQueue.executeNext_ (C:\mypro\node_m
odules\selenium-webdriver\lib\promise.js:2953:27)
        at asyncRun (C:\mypro\node_modules\seleniu
m-webdriver\lib\promise.js:2813:27)
        at C:\mypro\node_modules\selenium-webdrive
r\lib\promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:103:7)
    From: Task: Run it("should display the search result when clicking on differ
ent deeplink for national data") in control flow
        at Object.<anonymous> (C:\mypro\node_modul
es\jasminewd2\index.js:94:19)
        at C:\mypro\node_modules\jasminewd2\index.
js:64:48
        at ControlFlow.emit (C:\mypro\node_modules
\selenium-webdriver\lib\events.js:62:21)
        at ControlFlow.shutdown_ (C:\mypro\node_mo
dules\selenium-webdriver\lib\promise.js:2565:10)
        at shutdownTask_.MicroTask (C:\mypro\node_
modules\selenium-webdriver\lib\promise.js:2490:53)
        at MicroTask.asyncRun (C:\mypro\node_modul
es\selenium-webdriver\lib\promise.js:2619:9)
    From asynchronous test:
    Error
        at Suite.<anonymous> (C:\mypro\e2e\spec\pf
-deeplink.spec.js:30:6)
        at Object.<anonymous> (C:\mypro\e2e\spec\p
f-deeplink.spec.js:7:1)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)

12 specs, 3 failures
Finished in 41.129 seconds

[16:31:38] I/launcher - 0 instance(s) of WebDriver still running
[16:31:38] I/launcher - chrome #01 failed 3 test(s)
[16:31:38] I/launcher - overall: 3 failed spec(s)
Closing report
[16:31:38] E/launcher - Process exited with error code 1

Using standard to parse output
Re-running tests: test attempt 2
Re-running the following test files:
C:\mypro\e2e\spec\pf-deeplink.spec.js
Report destination:   e2e\testreports\e2eReport.html
[16:31:41] W/driverProviders - Using driver provider directConnect, but also fou
nd extra driver provider parameter(s): seleniumServerJar
[16:31:41] I/launcher - Running 1 instances of WebDriver
[16:31:41] I/direct - Using ChromeDriver directly...
```
[log.txt](https://github.com/NickTomlin/protractor-flake/files/1316027/log.txt)

I am not sure what's happening. Would you please look into it? Thanks

**Comment by wswebcreation** [comment]
Hi @surendraJ 

It only finds 1 spec because the regex of the standard parser is only matching on `at Object.<anonymous> (C:\mypro\e2e\spec\pf-deeplink.spec.js:7:1)`, see this [example](https://regex101.com/r/STPl7D/1)

The strange thing is that the second failed specs has this line `at Suite.<anonymous> (C:\mypro\e2e\spec\pf-deeplink.spec.js:30:6)` but you never define a `suite` in your config.

@NickTomlin Have you seen this behaviour?

@surendraJ 

You can fix this with a workaround by writing a custom parser as a copy from the [standard.js](https://github.com/NickTomlin/protractor-flake/blob/master/src/parsers/standard.js) and change line [https://github.com/NickTomlin/protractor-flake/blob/master/src/parsers/standard.js#L7] to `at (?:\[object Object\]|Object|UserContext|Suite)\.(?:<anonymous>|it) \((([A-Za-z]:\\)?.*?):.*\)`. Then it will also find the file with the `Suite`. To see this in action see [here](https://regex101.com/r/STPl7D/2)

**Comment by surendraJ** [comment]
@wswebcreation Thanks for your resources and pointing out to custom parser. From above log I have two situation that I can address to regex,  
1)  Error: Failed expectation
        at C:\mypro\e2e\spec\national-data-filter
2) at Suite.<anonymous> (C:\mypro\e2e\spec\pf
-deeplink.spec.js:30:6)

I am really wondering if this is the situation then how we would know which case will through which error. We don't have any common error message in error log. Do you think it is good to make such case by case regex for custom parser where we don't have any idea about pattern of error log?

**Comment by wswebcreation** [comment]
I think the problem is in you HtmlScreenshotReporter. Try to or disable it, or let it log stacktrace to the log. Because that is what protractor-flake needs

**Comment by surendraJ** [comment]
I tried with **jasmine-spec-reporter** by disabling **html screen shot reporter** and still getting same error log.  
```
onPrepare: function () {
    jasmine.getEnv().addReporter(new SpecReporter({
      spec: {
        displayStacktrace: true
      }
    ........
```

**Comment by wswebcreation** [comment]
Hmm, that is strange. Do you also have an example project where we can check this?

**Comment by surendraJ** [comment]
I don't have right now to publish here but I can prepare something by weekend. Expectation failed error never matching any pattern at (?:\[object Object\]|Object|UserContext)\.(?:<anonymous>|it)

In protractor code looks like this,  
`expect(text).toContain('(0)', 'expecting data has 0 data'); `

**Comment by wswebcreation** [comment]
Tnx in advance

**Comment by surendraJ** [comment]
I am going to close this issue since expectation error log from inside the promise never match with standard parser pattern. This issue similar with [issue-15](https://github.com/NickTomlin/protractor-flake/issues/15). 

For now we have to use custom parser to match those. It would be good if we can include these to standard parser.
